### ISSUE TITLE
Should the role be capitalized in the example?

### ISSUE THREAD

**Issue by asfarley** [Oefenweb/ansible-yarn#10]
The exact text in the example for this role on Ansible Galaxy is:

```
---
- hosts: all
  roles:
    - Oefenweb.yarn
```

When I use the above, I get an error: Oefenweb.yarn is not found. If I replace 'Oefenweb' with 'oefenweb' it works fine.

**Comment by tersmitten** [comment]
5105112c3974c86c12992c944a495386dbc12ca4
