### ISSUE TITLE
Can you please fix the build failing. 

### ISSUE THREAD

**Issue by pythonmobile** [Oefenweb/ansible-yarn#7]
Also, yarn/nodejs is broken on ubuntu 16.04 LTS currently. Please test on that if possible.

**Comment by tersmitten** [comment]
Can you add some more information?

**Comment by tersmitten** [comment]
The failing test can easily be fixed, it's just some ansible-lint warnings.

**Comment by pythonmobile** [comment]
Thanks. I will try it out. Currently I just put in the deb sources in my file to install yarn on ubuntu - that works.

**Comment by tersmitten** [comment]
fixed in #11
