### ISSUE TITLE
"Failed to update apt cache" due to yarn key issues

### ISSUE THREAD

**Issue by markdorison** [Oefenweb/ansible-yarn#9]
The debian yarn key expired and was replaced: https://github.com/yarnpkg/yarn/issues/7866

If this role had been run on a box previously and is now run again, it will fail with the following error:

```
TASK [oefenweb.yarn : repository | install dependencies (pre)] *******************************************************
task path: /.ansible/roles/oefenweb.yarn/tasks/repository.yml:3
fatal: [FQDN]: FAILED! => changed=false 
  msg: 'Failed to update apt cache: '
```

**Comment by tersmitten** [comment]
https://github.com/yarnpkg/yarn/issues/6865#issuecomment-450789338

**Comment by tersmitten** [comment]
I'm not sure if it needs a fix on this side. Possibly download another key.

Can you have a look at it?

**Comment by markdorison** [comment]
I know I could resolve this manually, but I was trying to avoid that. I wanted the steps to be reproducible by ansible. If you think this is out of scope for this role I understand, but I wanted to report it as this does seem limited in scope to yarn.

**Comment by tersmitten** [comment]
Due to inactivity
